name: "CI/CD"

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  Linting:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: sudo apt-get install -y cppcheck

      - name: Build project
        run: |
          make

      - name: Run linting
        run: cppcheck --quiet --error-exitcode=1 .

      - name: Run tests
        run: |
          ctest --output-on-failure

  Build-Image:
    runs-on: ubuntu-latest
    needs: Linting

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2.2.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/wpp:latest

  push-to-ecr:
    needs: Build-Image
    runs-on: ubuntu-latest

    steps:
      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-1
        env:
          AWS_AUDIENCE: sts.amazonaws.com

      - name: Login to Amazon ECR
        run: aws ecr get-login-password --region ${{ env.AWS_REGION }} | docker login --username AWS --password-stdin ${{ env.ECR_REGISTRY }}

      - name: Tag and push Docker image to ECR
        run: |
          docker tag wpp:latest public.ecr.aws/q6y0k8g3/hello-2048-lab:latest
          docker push public.ecr.aws/q6y0k8g3/hello-2048-lab:latest

  run-on-ecs:
    needs: push-to-ecr
    runs-on: ubuntu-latest

    steps:
      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-1
        env:
          AWS_AUDIENCE: sts.amazonaws.com

      - name: Run Docker container on ECS
        run: |
          aws ecs run-task \
            --cluster cpp-cluster \
            --launch-type FARGATE \
            --task-definition cpp-docker-instance \
            --network-configuration awsvpcConfiguration={subnets=[subnet-0818b9561675ff47e]}
